/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_witness_informa_wrappers_JpegWrapper */

#ifndef _Included_org_witness_informa_wrappers_JpegWrapper
#define _Included_org_witness_informa_wrappers_JpegWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_witness_informa_wrappers_JpegWrapper
 * Method:    getMetadata
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_witness_informa_wrappers_JpegWrapper_getMetadata
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_witness_informa_wrappers_JpegWrapper
 * Method:    unpackRegion
 * Signature: (Ljava/lang/String;II)[B
 */
//JNIEXPORT jbyteArray JNICALL Java_org_witness_informa_wrappers_JpegWrapper_unpackRegion
 // (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     org_witness_informa_wrappers_JpegWrapper
 * Method:    sayHi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_witness_informa_wrappers_JpegWrapper_sayHi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
